Parameters:
  LambdaS3Bucket:
    Type: String
  LambdaFunctionZip:
    Type: String
  DisableRuleFunctionZip:
    Type: String

Resources:
  CreateEventLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'lambda_function.lambda_handler'
      Role: 'arn:aws:iam::728939754004:role/LambdaEventBridgeRole'  # Replace 'YOUR_ACCOUNT_ID' and 'YOUR_LAMBDA_ROLE' with your actual AWS account ID and IAM role
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaFunctionZip
      Runtime: 'python3.8'

  DisableOldRuleLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'disable_rule.lambda_handler'
      Role: 'arn:aws:iam::728939754004:role/LambdaEventBridgeRole'  # Replace 'YOUR_ACCOUNT_ID' and 'YOUR_LAMBDA_ROLE' with your actual AWS account ID and IAM role
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref DisableRuleFunctionZip
      Runtime: 'python3.8'
