name: Deploy SageMaker Endpoint and EventBridge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Delete existing stack if in ROLLBACK_COMPLETE state
      run: |
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name Justin-test-SageMakerInferenceStack --query "Stacks[0].StackStatus" --output text || echo "NO_STACK")
        if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ]; then
          aws cloudformation delete-stack --stack-name Justin-test-SageMakerInferenceStack
          echo "Deleted stack in ROLLBACK_COMPLETE state."
          aws cloudformation wait stack-delete-complete --stack-name Justin-test-SageMakerInferenceStack
        elif [ "$STACK_STATUS" = "NO_STACK" ]; then
          echo "No existing stack found."
        else
          echo "Stack exists but not in ROLLBACK_COMPLETE state: $STACK_STATUS"
        fi

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy --template-file template.yaml --stack-name Justin-test-SageMakerInferenceStack --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

    - name: Enable EventBridge rule
      run: |
        aws events enable-rule --name Justin-test-SageMakerInferenceRule

    - name: Check EventBridge Rule Status
      run: |
        aws events describe-rule --name Justin-test-SageMakerInferenceRule
