name: Deploy Lambda and EventBridge

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install required Python packages from requirements.txt
        pip install jupyter  # Install Jupyter to run the notebook

    # Step 4: Create deployment package for CreateEventLambdaFunction
    - name: Create deployment package for CreateEventLambdaFunction
      run: |
        cd lambda_functions
        zip -r ../lambda_function.zip lambda_function.py  # Zip the lambda_function.py file
      working-directory: .

    # Step 5: Create deployment package for DisableOldRuleLambdaFunction
    - name: Create deployment package for DisableOldRuleLambdaFunction
      run: |
        cd lambda_functions
        zip -r ../disable_rule.zip disable_rule.py  # Zip the disable_rule.py file
      working-directory: .

    # Step 6: Upload Lambda functions to S3
    - name: Upload Lambda functions to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use AWS Access Key ID stored in GitHub Secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use AWS Secret Access Key stored in GitHub Secrets
        AWS_REGION: us-east-1  # Specify the AWS region
      run: |
        aws s3 cp lambda_function.zip s3://justin-lambda-functions-bucket/lambda_function.zip  # Upload the lambda_function.zip to S3
        aws s3 cp disable_rule.zip s3://justin-lambda-functions-bucket/disable_rule.zip  # Upload the disable_rule.zip to S3

    # Step 7: Deploy CloudFormation stack
    - name: Deploy CloudFormation stack
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use AWS Access Key ID stored in GitHub Secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use AWS Secret Access Key stored in GitHub Secrets
        AWS_REGION: us-east-1  # Specify the AWS region
      run: |
        aws cloudformation deploy \
          --template-file cloudformation_template.yaml \
          --stack-name eventbridge-lambda-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            LambdaS3Bucket=justin-lambda-functions-bucket \
            LambdaFunctionZip=lambda_function.zip \
            DisableRuleFunctionZip=disable_rule.zip


